modLoader="javafml" #mandatory
loaderVersion="[37,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
issueTrackerURL="https://github.com/aurilisdev/Electrodynamics" #optional
[[mods]] #mandatory
modId="electrodynamics" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Electrodynamics" #mandatory
displayURL="https://github.com/aurilisdev/Electrodynamics" #optional
logoFile="electrodynamics.png" #optional
credits="Thanks to all contributors" #optional
authors="aurilisdev" #optional
description='''
'''